name: Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter-check:
    name: Run Flutter Quality Checks
    runs-on: ubuntu-latest

    steps:
    # Paso para hacer checkout del código
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso para configurar JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'  # Puedes usar 'adoptopenjdk' o 'zulu'

    # Paso para configurar Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'  # Aquí estamos utilizando una versión compatible con Dart 3.5.3 o superior

    # Paso para instalar las dependencias de Flutter
    - name: Install dependencies
      run: flutter pub get

    # Paso para comprobar el formato del código
    - name: Check formatting
      run: flutter format --set-exit-if-changed .

    # Paso para construir la app
    - name: Build the app
      run: flutter build apk  # O usa otro comando de build que necesites

    # Paso para cachear las dependencias de Flutter
    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: ~/.pub-cache
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter-
