name: Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter-check:
    name: Run Flutter Quality Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4' # Aquí estamos utilizando una versión compatible con Dart 3.5.3 o superior

    - name: Install dependencies
      run: flutter pub get

    

    
    - name: Build the app
      run: flutter build apk # O usa otro comando de build que necesites

    - name: Check formatting
      run: flutter format --set-exit-if-changed .

    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: ~/.pub-cache
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter-
